//! Cross-language wire-format check.
//!
//! `forge-crypto` (RustCrypto `crypto_box`) and the PWA (TweetNaCl `nacl.box`)
//! have to produce bytes each other can open. Both are NaCl `crypto_box`, so
//! they should — but a silent incompatibility here would look like "the phone
//! can't approve anything" with no error pointing at the cause.
//!
//! So a fixture is checked in and *both* languages open it: this test, and
//! `packages/client-core/src/crypto.test.ts`. It carries one envelope sealed by each side, so a
//! regression in either direction fails.
//!
//! Regenerate with `cargo test -p forge-crypto --test interop -- --ignored`
//! after any change to the envelope format, then re-run the JS test.

use std::path::PathBuf;

use forge_crypto::{Envelope, Identity, PublicKey};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
struct Fixture {
    runner_secret: String,
    runner_public: String,
    device_secret: String,
    device_public: String,
    channel: String,
    /// Sealed by the runner, opened by the device.
    runner_to_device: Envelope,
    /// The plaintext inside it.
    runner_to_device_plaintext: String,
    /// Sealed by the device (generated by TweetNaCl), opened by the runner.
    device_to_runner: Envelope,
    device_to_runner_plaintext: String,
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/interop.json")
}

fn load() -> Fixture {
    let raw = std::fs::read_to_string(fixture_path()).expect(
        "tests/fixtures/interop.json is missing — regenerate it with \
         `cargo test -p forge-crypto --test interop -- --ignored`",
    );
    serde_json::from_str(&raw).expect("fixture is not valid JSON")
}

#[test]
fn rust_opens_the_envelope_rust_sealed() {
    let fixture = load();
    let device = Identity::from_secret_base64(&fixture.device_secret).unwrap();
    let runner_public = PublicKey::parse(&fixture.runner_public).unwrap();

    let opened = device
        .open(&runner_public, &fixture.runner_to_device)
        .unwrap();
    assert_eq!(
        String::from_utf8(opened).unwrap(),
        fixture.runner_to_device_plaintext
    );
}

#[test]
fn rust_opens_the_envelope_tweetnacl_sealed() {
    // This is the direction that actually proves interoperability: the
    // ciphertext was produced by the JavaScript implementation.
    let fixture = load();
    let runner = Identity::from_secret_base64(&fixture.runner_secret).unwrap();
    let device_public = PublicKey::parse(&fixture.device_public).unwrap();

    let opened = runner
        .open(&device_public, &fixture.device_to_runner)
        .unwrap();
    assert_eq!(
        String::from_utf8(opened).unwrap(),
        fixture.device_to_runner_plaintext
    );
}

#[test]
fn the_fixture_keys_match_their_public_halves() {
    let fixture = load();
    assert_eq!(
        Identity::from_secret_base64(&fixture.runner_secret)
            .unwrap()
            .public_key()
            .as_str(),
        fixture.runner_public
    );
    assert_eq!(
        Identity::from_secret_base64(&fixture.device_secret)
            .unwrap()
            .public_key()
            .as_str(),
        fixture.device_public
    );
}

/// Mint fresh keys and the Rust-sealed half. The TweetNaCl-sealed half is filled
/// in by `app/scripts/seal-fixture.mjs`, which reads this file and writes it back.
#[test]
#[ignore = "regenerates a checked-in fixture; run deliberately"]
fn regenerate() {
    let runner = Identity::generate();
    let device = Identity::generate();
    let channel = "forge-interop";

    let runner_to_device_plaintext =
        r#"{"type":"approval_request","tool":"Bash","payload":"pytest -x"}"#.to_owned();
    let runner_to_device = runner
        .seal(
            channel,
            "runner",
            device.public_key(),
            runner_to_device_plaintext.as_bytes(),
        )
        .unwrap();

    // Placeholder: the JS script replaces this half.
    let device_to_runner_plaintext =
        r#"{"type":"decide","approval_id":"a1","decision":"approved"}"#.to_owned();
    let device_to_runner = device
        .seal(
            channel,
            "device-phone",
            runner.public_key(),
            device_to_runner_plaintext.as_bytes(),
        )
        .unwrap();

    let fixture = Fixture {
        runner_secret: runner.to_secret_base64(),
        runner_public: runner.public_key().to_string(),
        device_secret: device.to_secret_base64(),
        device_public: device.public_key().to_string(),
        channel: channel.to_owned(),
        runner_to_device,
        runner_to_device_plaintext,
        device_to_runner,
        device_to_runner_plaintext,
    };

    std::fs::create_dir_all(fixture_path().parent().unwrap()).unwrap();
    std::fs::write(
        fixture_path(),
        serde_json::to_string_pretty(&fixture).unwrap(),
    )
    .unwrap();
    println!("wrote {}", fixture_path().display());
}
