/**
 * The JavaScript half of the cross-language wire-format check.
 *
 * The fixture is generated by Rust (`crates/forge-crypto/tests/interop.rs`) and
 * carries one envelope sealed by each language. Rust asserts it can open both;
 * so does this. A silent incompatibility between RustCrypto's `crypto_box` and
 * TweetNaCl's `nacl.box` would otherwise show up as "the phone can't approve
 * anything", with nothing pointing at the cause.
 */

import { describe, expect, it } from "vitest";
import fixture from "../../../crates/forge-crypto/tests/fixtures/interop.json";
import {
  CryptoError,
  Identity,
  fromBase64Url,
  parseOffer,
  toBase64Url,
  type Envelope,
} from "./index.ts";

const decode = (bytes: Uint8Array) => new TextDecoder().decode(bytes);

describe("interoperability with forge-crypto", () => {
  it("opens an envelope the Rust runner sealed", () => {
    const device = Identity.fromSecret(fixture.device_secret);
    const opened = device.open(
      fixture.runner_public,
      fixture.runner_to_device as Envelope,
    );
    expect(decode(opened)).toBe(fixture.runner_to_device_plaintext);
  });

  it("derives the same public key Rust derived from the same secret", () => {
    expect(Identity.fromSecret(fixture.device_secret).publicKey).toBe(
      fixture.device_public,
    );
    expect(Identity.fromSecret(fixture.runner_secret).publicKey).toBe(
      fixture.runner_public,
    );
  });

  it("seals something the Rust side can open", () => {
    // The fixture's device→runner half was produced by this implementation and
    // is asserted openable by Rust in `interop.rs`. Re-opening it here confirms
    // the two tests are looking at the same bytes.
    const runner = Identity.fromSecret(fixture.runner_secret);
    const opened = runner.open(
      fixture.device_public,
      fixture.device_to_runner as Envelope,
    );
    expect(decode(opened)).toBe(fixture.device_to_runner_plaintext);
  });
});

describe("base64url", () => {
  it("round-trips arbitrary bytes", () => {
    const bytes = new Uint8Array([0, 1, 250, 251, 252, 253, 254, 255]);
    expect(fromBase64Url(toBase64Url(bytes))).toEqual(bytes);
  });

  it("emits the unpadded url-safe alphabet Rust expects", () => {
    // 0xff 0xfe 0xfd encodes to characters that differ between the standard and
    // url-safe alphabets, which is exactly where a mismatch would hide.
    const encoded = toBase64Url(new Uint8Array([255, 254, 253]));
    expect(encoded).not.toContain("+");
    expect(encoded).not.toContain("/");
    expect(encoded).not.toContain("=");
  });

  it("decodes what Rust produced", () => {
    expect(fromBase64Url(fixture.runner_public)).toHaveLength(32);
  });
});

describe("sealing", () => {
  const channel = "chan";

  it("round-trips between two identities", () => {
    const runner = Identity.generate();
    const phone = Identity.generate();

    const envelope = runner.sealJson(channel, "runner", phone.publicKey, {
      hello: "world",
    });
    expect(phone.openJson(runner.publicKey, envelope)).toEqual({
      hello: "world",
    });
  });

  it("refuses an envelope from the wrong sender", () => {
    const runner = Identity.generate();
    const phone = Identity.generate();
    const attacker = Identity.generate();

    const forged = attacker.sealJson(channel, "runner", phone.publicKey, {
      decision: "approved",
    });
    expect(() => phone.openJson(runner.publicKey, forged)).toThrow(CryptoError);
  });

  it("detects a tampered ciphertext", () => {
    const runner = Identity.generate();
    const phone = Identity.generate();
    const envelope = runner.sealJson(channel, "runner", phone.publicKey, {
      a: 1,
    });

    const bytes = fromBase64Url(envelope.ciphertext);
    bytes[0] = (bytes[0] ?? 0) ^ 1;
    expect(() =>
      phone.openJson(runner.publicKey, {
        ...envelope,
        ciphertext: toBase64Url(bytes),
      }),
    ).toThrow(CryptoError);
  });

  it("uses a fresh nonce per message", () => {
    const runner = Identity.generate();
    const phone = Identity.generate();
    const first = runner.sealJson(channel, "runner", phone.publicKey, { a: 1 });
    const second = runner.sealJson(channel, "runner", phone.publicKey, { a: 1 });

    expect(first.nonce).not.toBe(second.nonce);
    expect(first.ciphertext).not.toBe(second.ciphertext);
  });

  it("keeps no plaintext in the envelope", () => {
    const runner = Identity.generate();
    const phone = Identity.generate();
    const envelope = runner.sealJson(channel, "runner", phone.publicKey, {
      command: "git push --force",
    });
    expect(JSON.stringify(envelope)).not.toContain("force");
  });

  it("survives a save and reload of the secret", () => {
    const original = Identity.generate();
    const restored = Identity.fromSecret(original.toSecret());
    expect(restored.publicKey).toBe(original.publicKey);
  });

  it("rejects a malformed secret rather than generating a new one", () => {
    expect(() => Identity.fromSecret("too-short")).toThrow(CryptoError);
  });
});

describe("pairing offers", () => {
  const validOffer = () =>
    JSON.stringify({
      relay_url: "ws://relay.example",
      channel: "forge-abc",
      runner_public_key: fixture.runner_public,
      code: "one-time-code",
      expires_at: Date.now() + 60_000,
    });

  it("parses a real offer", () => {
    const offer = parseOffer(validOffer());
    expect(offer.channel).toBe("forge-abc");
    expect(offer.runner_public_key).toBe(fixture.runner_public);
  });

  it("rejects something that is not JSON", () => {
    expect(() => parseOffer("just some text")).toThrow(CryptoError);
  });

  it("rejects an offer missing its runner key", () => {
    expect(() => parseOffer(JSON.stringify({ channel: "c", code: "x" }))).toThrow(
      CryptoError,
    );
  });

  it("rejects a malformed runner key before anything is stored", () => {
    expect(() =>
      parseOffer(
        JSON.stringify({
          channel: "c",
          code: "x",
          runner_public_key: toBase64Url(new Uint8Array(16)),
        }),
      ),
    ).toThrow(CryptoError);
  });

  it("rejects an expired code with an actionable message", () => {
    const expired = JSON.stringify({
      channel: "c",
      code: "x",
      runner_public_key: fixture.runner_public,
      expires_at: Date.now() - 1,
    });
    expect(() => parseOffer(expired)).toThrow(/expired/);
  });
});
