import Foundation
import Testing

@testable import ForgeCrypto

/// The Swift third of the cross-language wire-format check.
///
/// Salsa20, Poly1305, and the HSalsa20 key derivation in this package are all
/// hand-written, because Apple ships none of them. Hand-written crypto that
/// only ever talks to itself is indistinguishable from correct — it round-trips
/// beautifully and interoperates with nothing. So the real assertion is this
/// one: open envelopes that **RustCrypto's audited `crypto_box`** sealed, and
/// produce ones it can open back.
///
/// The fixture is generated by `crates/forge-crypto/tests/interop.rs` and shared
/// with `packages/client-core/src/crypto.test.ts`, so all three implementations
/// are checked against the same bytes.
struct Fixture: Decodable {
    let runnerSecret: String
    let runnerPublic: String
    let deviceSecret: String
    let devicePublic: String
    let channel: String
    let runnerToDevice: Envelope
    let runnerToDevicePlaintext: String
    let deviceToRunner: Envelope
    let deviceToRunnerPlaintext: String

    enum CodingKeys: String, CodingKey {
        case runnerSecret = "runner_secret"
        case runnerPublic = "runner_public"
        case deviceSecret = "device_secret"
        case devicePublic = "device_public"
        case channel
        case runnerToDevice = "runner_to_device"
        case runnerToDevicePlaintext = "runner_to_device_plaintext"
        case deviceToRunner = "device_to_runner"
        case deviceToRunnerPlaintext = "device_to_runner_plaintext"
    }

    /// Read the fixture where the Rust crate writes it.
    ///
    /// `#filePath` is this file's location at compile time; the repo root is
    /// four directories up. Reading the canonical file rather than a copied
    /// resource means the fixture can never silently go stale — which is the one
    /// failure mode that would make every test in this file meaningless.
    static func load() throws -> Fixture {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // ForgeCryptoTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // watch
            .deletingLastPathComponent()  // mobile
            .deletingLastPathComponent()  // <repo root>
            .appendingPathComponent("crates/forge-crypto/tests/fixtures/interop.json")

        guard FileManager.default.fileExists(atPath: url.path) else {
            Issue.record(
                """
                the interop fixture is missing at \(url.path) — regenerate it with
                  cargo test -p forge-crypto --test interop -- --ignored
                  node packages/client-core/scripts/seal-fixture.mjs
                """
            )
            throw CocoaError(.fileNoSuchFile)
        }
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }
}

@Suite("interoperability with forge-crypto")
struct InteropTests {
    @Test("opens an envelope the Rust runner sealed")
    func opensRustEnvelope() throws {
        let fixture = try Fixture.load()
        let device = try Identity.fromSecret(fixture.deviceSecret)

        let opened = try device.open(
            senderPublicKey: fixture.runnerPublic,
            envelope: fixture.runnerToDevice
        )
        #expect(String(decoding: opened, as: UTF8.self) == fixture.runnerToDevicePlaintext)
    }

    @Test("opens an envelope TweetNaCl sealed")
    func opensJavaScriptEnvelope() throws {
        // The device→runner half of the fixture was produced by the TypeScript
        // client. Three implementations, one wire format.
        let fixture = try Fixture.load()
        let runner = try Identity.fromSecret(fixture.runnerSecret)

        let opened = try runner.open(
            senderPublicKey: fixture.devicePublic,
            envelope: fixture.deviceToRunner
        )
        #expect(String(decoding: opened, as: UTF8.self) == fixture.deviceToRunnerPlaintext)
    }

    @Test("derives the public key Rust derived from the same secret")
    func derivesSamePublicKey() throws {
        let fixture = try Fixture.load()
        #expect(try Identity.fromSecret(fixture.deviceSecret).publicKey == fixture.devicePublic)
        #expect(try Identity.fromSecret(fixture.runnerSecret).publicKey == fixture.runnerPublic)
    }

    @Test("derives the same shared key in both directions")
    func sharedKeyAgrees() throws {
        // If HSalsa20 were skipped after the X25519 agreement, this would still
        // pass — but `opensRustEnvelope` would not. Both matter.
        let fixture = try Fixture.load()
        let runnerSecret = try Base64URL.decode(fixture.runnerSecret)
        let deviceSecret = try Base64URL.decode(fixture.deviceSecret)

        let fromRunner = try CryptoBox.sharedKey(
            secretKey: runnerSecret,
            publicKey: Base64URL.decode(fixture.devicePublic)
        )
        let fromDevice = try CryptoBox.sharedKey(
            secretKey: deviceSecret,
            publicKey: Base64URL.decode(fixture.runnerPublic)
        )
        #expect(fromRunner == fromDevice)
    }

    @Test("seals something the same keys open")
    func sealsWhatRustCanOpen() throws {
        let fixture = try Fixture.load()
        let watch = try Identity.fromSecret(fixture.deviceSecret)
        let runner = try Identity.fromSecret(fixture.runnerSecret)

        let envelope = try watch.seal(
            channel: fixture.channel,
            senderID: "watch",
            recipientPublicKey: fixture.runnerPublic,
            plaintext: Array("approve".utf8)
        )
        let opened = try runner.open(senderPublicKey: fixture.devicePublic, envelope: envelope)
        #expect(String(decoding: opened, as: UTF8.self) == "approve")
    }
}

@Suite("sealing")
struct SealingTests {
    let channel = "chan"

    @Test("round-trips between two identities")
    func roundTrips() throws {
        let runner = Identity.generate()
        let watch = Identity.generate()

        let envelope = try runner.seal(
            channel: channel,
            senderID: "runner",
            recipientPublicKey: watch.publicKey,
            plaintext: Array("hello".utf8)
        )
        let opened = try watch.open(senderPublicKey: runner.publicKey, envelope: envelope)
        #expect(String(decoding: opened, as: UTF8.self) == "hello")
    }

    @Test("refuses an envelope from the wrong sender")
    func rejectsWrongSender() throws {
        let runner = Identity.generate()
        let watch = Identity.generate()
        let attacker = Identity.generate()

        let forged = try attacker.seal(
            channel: channel,
            senderID: "runner",
            recipientPublicKey: watch.publicKey,
            plaintext: Array("approved".utf8)
        )
        #expect(throws: CryptoError.decryptionFailed) {
            try watch.open(senderPublicKey: runner.publicKey, envelope: forged)
        }
    }

    @Test("detects a tampered ciphertext")
    func detectsTampering() throws {
        let runner = Identity.generate()
        let watch = Identity.generate()
        let envelope = try runner.seal(
            channel: channel,
            senderID: "runner",
            recipientPublicKey: watch.publicKey,
            plaintext: Array("deny".utf8)
        )

        var bytes = try Base64URL.decode(envelope.ciphertext)
        bytes[bytes.count - 1] ^= 1
        let tampered = Envelope(
            channel: envelope.channel,
            senderID: envelope.senderID,
            nonce: envelope.nonce,
            ciphertext: Base64URL.encode(bytes)
        )

        #expect(throws: CryptoError.decryptionFailed) {
            try watch.open(senderPublicKey: runner.publicKey, envelope: tampered)
        }
    }

    @Test("detects a tampered tag")
    func detectsTagTampering() throws {
        let runner = Identity.generate()
        let watch = Identity.generate()
        let envelope = try runner.seal(
            channel: channel,
            senderID: "runner",
            recipientPublicKey: watch.publicKey,
            plaintext: Array("deny".utf8)
        )

        // Byte 0 is inside the Poly1305 tag, not the ciphertext.
        var bytes = try Base64URL.decode(envelope.ciphertext)
        bytes[0] ^= 1
        let tampered = Envelope(
            channel: envelope.channel,
            senderID: envelope.senderID,
            nonce: envelope.nonce,
            ciphertext: Base64URL.encode(bytes)
        )

        #expect(throws: CryptoError.decryptionFailed) {
            try watch.open(senderPublicKey: runner.publicKey, envelope: tampered)
        }
    }

    @Test("uses a fresh nonce per message")
    func freshNonce() throws {
        let runner = Identity.generate()
        let watch = Identity.generate()
        let first = try runner.seal(
            channel: channel, senderID: "runner",
            recipientPublicKey: watch.publicKey, plaintext: Array("a".utf8))
        let second = try runner.seal(
            channel: channel, senderID: "runner",
            recipientPublicKey: watch.publicKey, plaintext: Array("a".utf8))

        // A repeated nonce under the same key is total loss for XSalsa20.
        #expect(first.nonce != second.nonce)
        #expect(first.ciphertext != second.ciphertext)
    }

    @Test("keeps no plaintext in the envelope")
    func noPlaintextLeaks() throws {
        let runner = Identity.generate()
        let watch = Identity.generate()
        let envelope = try runner.seal(
            channel: channel,
            senderID: "runner",
            recipientPublicKey: watch.publicKey,
            plaintext: Array(#"{"command":"git push --force"}"#.utf8)
        )
        let encoded = String(decoding: try JSONEncoder().encode(envelope), as: UTF8.self)
        #expect(!encoded.contains("force"))
    }

    @Test("survives a save and reload of the secret")
    func survivesReload() throws {
        let original = Identity.generate()
        let restored = try Identity.fromSecret(original.toSecret())
        #expect(restored.publicKey == original.publicKey)
    }

    @Test("rejects a malformed secret rather than generating a new one")
    func rejectsBadSecret() {
        #expect(throws: CryptoError.self) { try Identity.fromSecret("too-short") }
    }

    @Test("round-trips an empty message")
    func emptyMessage() throws {
        // Zero-length plaintext is the edge case where the "start at offset 32"
        // rule and the Poly1305 padding rule both have nothing to work on.
        let runner = Identity.generate()
        let watch = Identity.generate()
        let envelope = try runner.seal(
            channel: channel, senderID: "runner",
            recipientPublicKey: watch.publicKey, plaintext: [])
        #expect(try watch.open(senderPublicKey: runner.publicKey, envelope: envelope).isEmpty)
    }

    @Test("round-trips messages across every block boundary")
    func blockBoundaries() throws {
        let runner = Identity.generate()
        let watch = Identity.generate()

        // Poly1305 works in 16-byte blocks and Salsa20 in 64-byte ones; the
        // keystream is offset by 32. Any off-by-one in that arithmetic shows up
        // at a boundary and nowhere else.
        for length in [1, 15, 16, 17, 31, 32, 33, 63, 64, 65, 96, 127, 128, 129] {
            let plaintext = (0..<length).map { UInt8($0 & 0xff) }
            let envelope = try runner.seal(
                channel: channel, senderID: "runner",
                recipientPublicKey: watch.publicKey, plaintext: plaintext)
            let opened = try watch.open(senderPublicKey: runner.publicKey, envelope: envelope)
            #expect(opened == plaintext, "length \(length)")
        }
    }
}

@Suite("base64url")
struct Base64URLTests {
    @Test("emits the url-safe alphabet, unpadded")
    func urlSafe() {
        let encoded = Base64URL.encode([255, 254, 253])
        #expect(encoded == "__79")
    }

    @Test("round-trips every length up to 64")
    func roundTrips() throws {
        for length in 0...64 {
            let bytes = (0..<length).map { UInt8(($0 * 37 + 11) & 0xff) }
            #expect(try Base64URL.decode(Base64URL.encode(bytes)) == bytes, "length \(length)")
        }
    }

    @Test("decodes what Rust produced")
    func decodesRust() throws {
        let fixture = try Fixture.load()
        #expect(try Base64URL.decode(fixture.runnerPublic).count == 32)
    }

    @Test("rejects a truncated group")
    func rejectsTruncated() {
        #expect(throws: CryptoError.notBase64URL) { try Base64URL.decode("AAAAA") }
    }
}
